### ISSUE TITLE
Update gradle and use mavenCentral() instead of jcenter()

### ISSUE THREAD

**Issue by DaemonChoejur** [aakashkondhalkar/external_path#6]
gradle update warning 

`./gradlew --warning-mode all` shows the following output for the package.

`..pub,dartlang.org/external_path-1.0.1/android' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.3/userguide/upgrading_version_7.html#deprecated_flat_project_structure
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.3/userguide/upgrading_version_6.html#jcenter_deprecation`

**Comment by aakashkondhalkar** [comment]
Fixed in latest release [external_path: ^1.0.3](https://pub.dev/packages/external_path)
